import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./shared/NavBar";
import Footer from "./shared/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <NavBar></NavBar>
        {children}
        <Footer></Footer>
        </body>
    </html>
  );
}
